### ISSUE TITLE
Implement Explosive Cannon

### ISSUE THREAD

**Issue by Pacted** [Kidel/BG3_Artificer#34]
better version of whatever we used as Eldritch Cannon

**Comment by Kidel** [comment]
need to make a separate summon with higher level spells, like we did on the battlesmith's defender. Then the summon spell will conditionally summon a different one based on artificer's level.

**Comment by Kidel** [comment]
done the skeleton and skills. Just needs some descriptions and to tone down the explosion. At the moment it's using `data "OnApplyFunctors" "CreateExplosion(Projectile_SteelWatcher_Quadruped_SelfDestructExplosion);Kill(SELF)"` 
So we just neet to create something instead of `Projectile_SteelWatcher_Quadruped_SelfDestructExplosion` (maybe use that but lower damage and with spell saving throw halving damage)
